import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Archive, Beaker, BookOpen, ChevronRight, CircleAlert, FileCheck2, Fingerprint, GitBranch, Home, LockKeyhole, Play, Search, Settings, ShieldCheck } from 'lucide-react';
import { CALIBRATION_STATUS, DocumentProvider, GitHubActionAdapter, consensus, createReceipt, decidePermission, mapAtomicClaims, semanticVerify, sha256 } from './core.js';
import './styles.css';

const sourceText = 'TraceNLI validates exact source spans before semantic verification. A successful API response does not establish a verified external effect. Missing evidence remains unresolved.';
const initialRuns = [{ id: 'RUN-2408-01', objective: 'Verify the release control description', status: 'PASS', claims: 3, time: '10:42 UTC' }, { id: 'RUN-2408-00', objective: 'Validate deployment completion claim', status: 'UNRESOLVED', claims: 2, time: '09:16 UTC' }];
const navigation = [['/', Home, 'New Verification'], ['/runs', Activity, 'Run history'], ['/sources', BookOpen, 'Source packs'], ['/evaluation', Beaker, 'Evaluation Lab'], ['/receipts', FileCheck2, 'Receipts'], ['/settings', Settings, 'Settings']];

function Badge({ children, tone = 'neutral' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function route() { return window.location.pathname; }
function Layout({ children }) {
  const [path, setPath] = useState(route());
  useEffect(() => { const pop = () => setPath(route()); window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop); }, []);
  const go = (event, href) => { event.preventDefault(); history.pushState({}, '', href); setPath(href); };
  return <div className="shell"><aside><div className="brand"><div className="mark"><Fingerprint /></div><div><strong>PINCH</strong><span>TraceNLI</span></div></div><nav>{navigation.map(([href, Icon, label]) => <a key={href} href={href} onClick={(e) => go(e, href)} className={(href === '/' ? path === '/' : path.startsWith(href)) ? 'active' : ''}><Icon />{label}</a>)}</nav><div className="constitutional"><LockKeyhole/><div><strong>Constitution active</strong><span>Transitions remain distinct</span></div></div></aside><main><header><div><span className="eyebrow">PROVENANCE-PRESERVING VERIFICATION</span><h1>{titleFor(path)}</h1></div><div className="system-state"><i></i> Local deterministic mode</div></header>{children(path)}</main></div>;
}
function titleFor(path) { if (path.startsWith('/runs/')) return 'Verification run'; return navigation.find(([href]) => href === path)?.[2] || 'TraceNLI'; }

function NewVerification({ onRun }) {
  const [candidate, setCandidate] = useState('TraceNLI validates exact source spans before semantic verification.');
  const [document, setDocument] = useState(sourceText); const [action, setAction] = useState('VERIFY_ONLY'); const [working, setWorking] = useState(false);
  const execute = async () => { setWorking(true); const provider = new DocumentProvider({ id: 'DOC-001', text: document, revision: await sha256(document) }); const claims = mapAtomicClaims(candidate); const decisions = [];
    for (const claim of claims) { const refs = provider.search(claim.text); const validated = refs[0] ? await provider.validate({ ...refs[0], evidence_id: `E${claim.claim_id.slice(1)}`, query: claim.text }, refs[0].candidate_span) : null; const packet = validated?.span_validation === 'VALIDATED' ? Object.freeze([validated]) : Object.freeze([]); const a = semanticVerify(claim, packet, { provider: 'local', model: 'lexical-a', prompt_version: 'A-1' }, { threshold: .55 }); const b = semanticVerify(claim, packet, { provider: 'local', model: 'lexical-b', prompt_version: 'B-1' }, { threshold: .62, independenceBoundary: 'B received claim and packet only; A output was withheld.' }); decisions.push({ claim, evidence: packet, verifier_a: a, verifier_b: b, consensus: consensus(a, b) }); }
    const permission = decidePermission(action, decisions.map((d) => d.consensus)); const receipt = await createReceipt({ run_id: `RUN-${Date.now()}`, objective: candidate, source_pack_fingerprint: await sha256(document), claim_ids: claims.map((c) => c.claim_id), evidence_ids: decisions.flatMap((d) => d.evidence.map((e) => e.evidence_id)), verifier_identities: decisions.flatMap((d) => [d.verifier_a.verifier_identity, d.verifier_b.verifier_identity]), verdicts: decisions.map((d) => ({ claim_id: d.claim.claim_id, a: d.verifier_a.verdict, b: d.verifier_b.verdict })), consensus: decisions.map((d) => d.consensus), permission, approval: null, requested_action: action, permitted_action: permission.permission_decision, attempted_action: null, tool_observation: null, postcondition_observation: null, audit_status: 'NOT_EXECUTED', unresolved_uncertainty: decisions.filter((d) => d.consensus.decision !== 'PASS').map((d) => d.claim.claim_id) }); onRun({ receipt, decisions, status: decisions.every((d) => d.consensus.decision === 'PASS') ? 'PASS' : decisions.some((d) => d.consensus.decision === 'BLOCK') ? 'BLOCK' : 'UNRESOLVED' }); setWorking(false); };
  return <section><div className="notice"><CircleAlert/><div><strong>Evidence, not truth</strong><span>This system produces auditable decision evidence. Retrieval, scores, and agreement do not establish factual truth.</span></div></div><div className="new-grid"><div className="panel compose"><div className="panel-title"><div><span className="step">01</span><div><h2>Candidate statement</h2><p>Enter prose to decompose into atomic, inspectable claims.</p></div></div><Badge>MODEL_DERIVED</Badge></div><textarea aria-label="Candidate text" value={candidate} onChange={(e) => setCandidate(e.target.value)} /><div className="field-row"><label>Requested action<select value={action} onChange={(e) => setAction(e.target.value)}><option>VERIFY_ONLY</option><option>CREATE_GITHUB_ISSUE_IF_VERIFIED</option><option>CREATE_GITHUB_ISSUE_WITH_UNCERTAINTY_DISCLOSED</option></select></label><button onClick={execute} disabled={!candidate.trim() || working}><Play/>{working ? 'Processing…' : 'Begin verification'}</button></div></div><div className="panel source"><div className="panel-title"><div><span className="step">02</span><div><h2>Source pack</h2><p>Canonical evidence is sliced only from these original bytes.</p></div></div><Badge tone="green">SOURCE INPUT</Badge></div><label>Document · DOC-001<textarea aria-label="Source document" value={document} onChange={(e) => setDocument(e.target.value)} /></label><div className="source-meta"><Fingerprint/> Revision fingerprint computed at run time</div></div></div><Pipeline/></section>;
}
function Pipeline() { const steps = ['Claim map', 'Retrieve', 'Validate span', 'Verifier A', 'Verifier B', 'Consensus', 'Permission', 'Audit', 'Receipt']; return <div className="pipeline"><div><span className="eyebrow">ENFORCED SEQUENCE</span><h2>No boundary may be bypassed</h2></div><div className="rail">{steps.map((step, i) => <React.Fragment key={step}><span>{String(i + 1).padStart(2, '0')}<b>{step}</b></span>{i < steps.length - 1 && <ChevronRight/>}</React.Fragment>)}</div></div>; }
function Runs({ runs, open }) { return <section className="panel"><div className="toolbar"><div><h2>Run ledger</h2><p>Durable local observations and deterministic decisions.</p></div><div className="search"><Search/> Filter runs</div></div><table><thead><tr><th>Run</th><th>Objective</th><th>Claims</th><th>Decision</th><th>Observed</th><th></th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td className="mono">{run.id}</td><td>{run.objective}</td><td>{run.claims}</td><td><Badge tone={run.status === 'PASS' ? 'green' : run.status === 'BLOCK' ? 'red' : 'amber'}>{run.status}</Badge></td><td>{run.time}</td><td><button className="icon-button" onClick={() => open(run.id)}><ChevronRight/></button></td></tr>)}</tbody></table></section>; }
function RunDetail({ run }) { if (!run?.decisions) return <Empty title="No local detail for this seeded run"/>; return <section><div className="run-head"><div><Badge tone={run.status === 'PASS' ? 'green' : 'amber'}>{run.status}</Badge><span className="mono">{run.receipt.run_id}</span></div><p>{run.receipt.objective}</p></div>{run.decisions.map((d) => <article className="claim-card" key={d.claim.claim_id}><div className="claim-id">{d.claim.claim_id}</div><div><h3>{d.claim.text}</h3><div className="evidence-quote">{d.evidence[0] ? <>“{d.evidence[0].exact_span}”<small>{d.evidence[0].source_id} · offsets {d.evidence[0].start_offset}–{d.evidence[0].end_offset} · {d.evidence[0].content_hash.slice(0, 14)}…</small></> : 'No validated evidence entered the packet.'}</div><div className="verifier-grid"><Verifier title="Semantic verifier A" data={d.verifier_a}/><Verifier title="LLM semantic verifier B" data={d.verifier_b}/><div className="decision"><span>DETERMINISTIC CONSENSUS</span><strong>{d.consensus.decision}</strong><p>{d.consensus.reason}</p><small>{CALIBRATION_STATUS}</small></div></div></div></article>)}</section>; }
function Verifier({ title, data }) { return <div className="verifier"><span>{title}</span><strong>{data.verdict}</strong><p>Raw decision signal {data.raw_model_score}</p><small>{data.independence_boundary}</small></div>; }
function Sources() { return <section className="cards"><div className="panel source-card"><BookOpen/><h2>Document provider</h2><p>Exact-match validation derives canonical evidence from original source slices and records offsets plus SHA-256 content hashes.</p><Badge tone="green">READ ONLY</Badge></div><div className="panel source-card"><GitBranch/><h2>GitHub snapshot provider</h2><p>Frozen commit SHA, repository path, line range, exact span, and hash remain attached to each evidence item.</p><Badge tone="green">READ ONLY</Badge></div><div className="panel source-card"><Archive/><h2>Immutable packet</h2><p>Invalid extraction candidates are excluded before either semantic verifier receives the packet.</p><Badge>BOUNDARY</Badge></div></section>; }
function Evaluation() { const cases = ['wrong claim', 'wrong evidence', 'negation', 'numeric mismatch', 'date mismatch', 'entity swap', 'partial support', 'irrelevant evidence', 'duplicate evidence', 'missing evidence', 'conflicting sources', 'substring trap', 'scope mismatch', 'fabricated passage', 'paraphrase as quote', 'verifier disagreement', 'verifier exception', 'prompt injection', 'unapproved write', 'unresolved + approval', 'POST + mismatched GET', 'POST + missing GET']; return <section><div className="metric-grid"><Metric label="Primary metric" value="False acceptance rate"/><Metric label="Calibration" value="Not empirically calibrated"/><Metric label="Layers" value="3 frozen partitions"/></div><div className="panel"><div className="toolbar"><div><h2>Frozen adversarial benchmark</h2><p>Expected labels are held outside prediction inputs. No benchmark results are claimed until the suite runs.</p></div><Badge>{cases.length} CASES</Badge></div><div className="case-grid">{cases.map((item, i) => <div key={item}><span className="mono">ADV-{String(i + 1).padStart(2, '0')}</span><b>{item}</b><Badge>FROZEN</Badge></div>)}</div></div></section>; }
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function Empty({ title }) { return <div className="panel empty"><ShieldCheck/><h2>{title}</h2><p>No stronger status is inferred from unavailable observations.</p></div>; }
function SettingsPage() { return <section className="panel settings"><h2>Bounded configuration</h2><div className="setting"><div><strong>Semantic verifier A</strong><span>local / lexical-a / A-1</span></div><Badge>INDEPENDENT INPUT</Badge></div><div className="setting"><div><strong>LLM semantic verifier B</strong><span>local / lexical-b / B-1</span></div><Badge>NOT GROUND TRUTH</Badge></div><div className="setting"><div><strong>GitHub action adapter</strong><span>No live connector configured; target allowlist empty</span></div><Badge tone="amber">NO WRITE AUTHORITY</Badge></div></section>; }

export default function App() { const [runs, setRuns] = useState(initialRuns); const [latest, setLatest] = useState(null); const content = (path) => { const open = (id) => { history.pushState({}, '', `/runs/${id}`); window.dispatchEvent(new PopStateEvent('popstate')); }; if (path === '/') return <NewVerification onRun={(run) => { setLatest(run); setRuns((old) => [{ id: run.receipt.run_id, objective: run.receipt.objective, status: run.status, claims: run.decisions.length, time: 'just now' }, ...old]); open(run.receipt.run_id); }}/>; if (path === '/runs') return <Runs runs={runs} open={open}/>; if (path.startsWith('/runs/')) return <RunDetail run={latest?.receipt.run_id === path.split('/').pop() ? latest : null}/>; if (path === '/sources') return <Sources/>; if (path === '/evaluation') return <Evaluation/>; if (path === '/receipts') return latest ? <section className="panel receipt"><h2>Latest verification receipt</h2><pre>{JSON.stringify(latest.receipt, null, 2)}</pre></section> : <Empty title="No receipts generated in this session"/>; if (path === '/settings') return <SettingsPage/>; return <Empty title="Route not found"/>; }; return <Layout>{content}</Layout>; }

export { GitHubActionAdapter };
